services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/nichwall/audiobook-censor:latest
    container_name: censor-try-1
    ports:
      - "8085:8000"
    restart: unless-stopped
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./transcripts:/app/transcripts
      - ./config:/app/config
    user: "1000:1000"
